<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>..\assets\GitLocal.ico</ApplicationIcon>
    <AssemblyName>GitLocal</AssemblyName>
    <RootNamespace>GitLocal</RootNamespace>
  </PropertyGroup>
</Project>
